name: build-discover-server
on: [push]
env: 
  DOCKER_REGISTRY: test
  APP_VERSION: latest
jobs: 
  build-java-app: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Set up JDK 17 for x64 
        uses: actions/setup-java@v3
        with: 
          distribution: oracle
          java-version: 17
          architecture: x64 
      - name: Build application
        run: mvn package -DskipTests
      - name: Build Docker image
        run: docker build --no-cache -t $DOCKER_REGISTRY:$APP_VERSION . 
