name: build-discover-server
on: [push]
jobs: 
  check-environment: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Set up JDK 17 for x64 
        uses: actions/setup-java@v3
        with: 
          distribution: oracle
          java-version: 17
          architecture: x64 
