name: build-discover-server
on: [push]
env: 
  DOCKER_REGISTRY: test
  APP_VERSION: latest
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ROLE: ${{ secrets.AWS_ASSUME_ROLE_NAME }}
jobs: 
  build-java-app: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Set up JDK 17 for x64 
        uses: actions/setup-java@v3
        with: 
          distribution: oracle
          java-version: 17
          architecture: x64 
      - name: Build application
        run: mvn package -DskipTests
      - name: Build Docker image
        run: docker build --no-cache -t $DOCKER_REGISTRY:$APP_VERSION . 
      - name: Config AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE }}
          aws-region: ap-southeast-1
        
